#Homework assignment #2

program: hw2.o quickSort.o bubbleSort.o
	gcc -o p1 hw2.o quickSort.o bubbleSort.o /Users/lopezlu/Projects/CS-270/HW2
hw2.o:
	gcc -c hw2.c
quickSort.o:
	gcc -c quickSort.c
bubbleSort.o:
	gcc -c bubbleSort.c
