#Homework assignment #2

program: hw2.o quickSort.o bubbleSort.o
	gcc -o p1 hw2.o quickSort.o bubbleSort.o
hw2.o: hw2.c
	gcc -c hw2.c
quickSort.o: quickSort.c
	gcc -c quickSort.c
bubbleSort.o: bubbleSort.c
	gcc -c bubbleSort.c
